### ISSUE TITLE
Remove ThisWeek Session when course is over  (and before starting?)

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2017#11]
Possibly replace it with the class picture?

**Comment by domenic** [comment]
Made it disappear, whenever you make the contents of the this-week.yml file `null`.

If you wanna do the class picture thing, upload it to the images directory and we can take it from there.

**Comment by domenic** [comment]
Hmm, deploy did not work for some credentials-related reason. We should work on this sometime when we're in the same room...
