### ISSUE TITLE
Indenting bullets?

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2017#6]
In the assignments section: file:///Users/drosen/Dropbox/repos/ml2017/index.html#assignments there's a numbered list, that might look better indented.

**Comment by domenic** [comment]
Should it be indented or changed from numbers to bullets or both?

**Comment by domenic** [comment]
Also note that we seem to have gone for out-of-margin bullets/numbers for all lists, e.g. in https://davidrosenberg.github.io/ml2017/#project too

**Comment by domenic** [comment]
Wait but not for https://davidrosenberg.github.io/ml2017/#about for some reason. OK, maybe something is funky here.

**Comment by davidrosenberg** [comment]
I think numbers are fine.  It's possible that all the out-of-margin lists were made by me, because I didn't know any better.

**Comment by domenic** [comment]
OK so we want uniform inside-margin for all numbers and bullets?

I'm betting it's our fault, but will check later. It's mysterious that some bullets stay inside the margin.

**Comment by davidrosenberg** [comment]
So uniform inside-margin makes sense to me -- I think it looks better.
